from nltk.stem import WordNetLemmatizer

wnl = WordNetLemmatizer()


print(wnl.lemmatize('hello'))
print(wnl.lemmatize('hi'))
print(wnl.lemmatize('hey' ))
print(wnl.lemmatize('your feeling'))
print(wnl.lemmatize('whats up'))
print(wnl.lemmatize('hows it going' ))
print(wnl.lemmatize('name'))
print(wnl.lemmatize('hows it going' ))
print(wnl.lemmatize('who created you'))
print(wnl.lemmatize('who is your creator'))
print(wnl.lemmatize('creator' ))
print(wnl.lemmatize('goodbye'))
print(wnl.lemmatize('bye'))
print(wnl.lemmatize('see you later' ))
print(wnl.lemmatize('weather'))
print(wnl.lemmatize('forecast'))
print(wnl.lemmatize('temperature' ))
print(wnl.lemmatize('thanks'))
print(wnl.lemmatize('thank you'))
print(wnl.lemmatize('appreciate it' ))
print(wnl.lemmatize('help'))
print(wnl.lemmatize('assistance'))
print(wnl.lemmatize('support' ))
print(wnl.lemmatize('age'))
print(wnl.lemmatize('old'))
print(wnl.lemmatize('birthday' ))
print(wnl.lemmatize('joke'))
print(wnl.lemmatize('funny'))
print(wnl.lemmatize('humor' ))
print(wnl.lemmatize('how are you' ))
print(wnl.lemmatize('what can you do'))
print(wnl.lemmatize('capability'))
print(wnl.lemmatize('ability' ))
print(wnl.lemmatize('where are you located'))
print(wnl.lemmatize('location'))
print(wnl.lemmatize('where do you live' ))
print(wnl.lemmatize('report'))
print(wnl.lemmatize('feedback' ))
print(wnl.lemmatize('what is your favorite color' ))
print(wnl.lemmatize('coal mine act'))
print(wnl.lemmatize('1952'))
print(wnl.lemmatize('the safety and working condition in coal mine'))
print(wnl.lemmatize('guideline for ensuring the well-being of coal mine workers and safe mining practice'))
print(wnl.lemmatize('identifying safety hazard, addressing violation, and continuously improving the safety of coal mining operation.' ))
print(wnl.lemmatize('indian explosives act'))
print(wnl.lemmatize('1884'))
print(wnl.lemmatize('significant legal framework'))
print(wnl.lemmatize('the safe handling, storage, transportation, and usage of explosives in mines'))
print(wnl.lemmatize('explosives are handled and utilized in a safe and lawful manner' ))
print(wnl.lemmatize('colliery control order'))
print(wnl.lemmatize('2000'))
print(wnl.lemmatize('regulatory framework'))
print(wnl.lemmatize('the production and sale of coal'))
print(wnl.lemmatize('tracking coal production, transportation, and sales, ensuring that these activity comply with the law'))
print(wnl.lemmatize('coal is distributed in accordance with legal provisions.' ))
print(wnl.lemmatize('colliery control rule'))
print(wnl.lemmatize('2004'))
print(wnl.lemmatize('the environmental aspect of coal mining'))
print(wnl.lemmatize('monitor and mitigate the environmental impacts of coal mining activity' ))
print(wnl.lemmatize('payment of wage (mines) rules'))
print(wnl.lemmatize('1956'))
print(wnl.lemmatize('the payment of wage, working hour, and other employment condition for worker in coal mines'))
print(wnl.lemmatize('worker in coal mining operation are paid fairly' ))
print(wnl.lemmatize('coal bearing areas (acquisition and development) act'))
print(wnl.lemmatize('1957'))
print(wnl.lemmatize('cba act'))
print(wnl.lemmatize('important legal framework'))
print(wnl.lemmatize('acquisition of land that contains or is likely to contain coal deposits' ))
print(wnl.lemmatize('the coal mines (special provisions) act'))
print(wnl.lemmatize('2015'))
print(wnl.lemmatize('important legal framework'))
print(wnl.lemmatize('facilitates the allocation of coal mines'))
print(wnl.lemmatize('allocation of coal mines and vests the right, title, and interest in coal-bearing areas'))
print(wnl.lemmatize('acquisition of land that contains or is likely to contain coal deposits' ))
print(wnl.lemmatize('the mines and minerals (development and regulation) act'))
print(wnl.lemmatize('1957'))
print(wnl.lemmatize('mmdr act'))
print(wnl.lemmatize('development and regulation of mines and minerals, including coal'))
print(wnl.lemmatize('critical legal framework' ))
print(wnl.lemmatize('the mines act'))
print(wnl.lemmatize('1952'))
print(wnl.lemmatize('key piece of legislation'))
print(wnl.lemmatize('safeguarding the well-being of workers employed in coal mines'))
print(wnl.lemmatize('regulations related to ventilation, safety equipment, working hours, and various other aspects' ))
print(wnl.lemmatize('the coal mines (conservation and development) act'))
print(wnl.lemmatize('1974'))
print(wnl.lemmatize('significant piece of legislation'))
print(wnl.lemmatize('conservation and efficient utilization of coal resources'))
print(wnl.lemmatize('provisions related to coal mining practices, storage, and transportation, with the aim of promoting sustainable development' ))
print(wnl.lemmatize('the environmental impact assessment notification'))
print(wnl.lemmatize('1994'))
print(wnl.lemmatize('eia'))
print(wnl.lemmatize('crucial policy instrument'))
print(wnl.lemmatize('environmental clearance process for various projects, including coal mining'))
print(wnl.lemmatize('environmental protection and sustainability' ))
print(wnl.lemmatize('the forest (conservation) act'))
print(wnl.lemmatize('1980'))
print(wnl.lemmatize('diversion of forestland for non-forest purposes, including mining activities'))
print(wnl.lemmatize('forested areas are conserved' ))
print(wnl.lemmatize('the water (prevention and control of pollution) act'))
print(wnl.lemmatize('1974'))
print(wnl.lemmatize('vital legislation'))
print(wnl.lemmatize('prevention and control of water pollution'))
print(wnl.lemmatize('compliance with environmental standards' ))
print(wnl.lemmatize('the air (prevention and control of pollution) act'))
print(wnl.lemmatize('1981'))
print(wnl.lemmatize('significant law'))
print(wnl.lemmatize('air quality standards and emissions'))
print(wnl.lemmatize('compliance with environmental standards'))
print(wnl.lemmatize('prevent and control air pollution' ))
print(wnl.lemmatize('the national mineral policy'))
print(wnl.lemmatize('2019'))
print(wnl.lemmatize('policy document'))
print(wnl.lemmatize('comprehensive framework for the management of mineral resources'))
print(wnl.lemmatize('sustainable mining practices, transparency'))
print(wnl.lemmatize('welfare of local communities impacted by mining' ))
print(wnl.lemmatize('the mines and minerals (development and regulation) amendment act'))
print(wnl.lemmatize('2015'))
print(wnl.lemmatize('crucial legislation'))
print(wnl.lemmatize('amended the mmdr act of 1957'))
print(wnl.lemmatize('major reforms in the allocation of mineral resources'))
print(wnl.lemmatize('promote efficiency, fairness, and sustainable mining practices' ))
print(wnl.lemmatize('the mineral (auction) rules'))
print(wnl.lemmatize('2015'))
print(wnl.lemmatize('procedural framework'))
print(wnl.lemmatize('conducting transparent auction, ensuring fairness and efficiency in resource allocation' ))
print(wnl.lemmatize('the national mineral exploration policy'))
print(wnl.lemmatize('2016'))
print(wnl.lemmatize('policy document'))
print(wnl.lemmatize('promote mineral exploration activities'))
print(wnl.lemmatize('reducing import dependency'))
print(wnl.lemmatize('enhancing resource availability'))
print(wnl.lemmatize('encouraging private sector participation in mineral exploration' ))
print(wnl.lemmatize('the district mineral foundation (dmf) rules'))
print(wnl.lemmatize('2015'))
print(wnl.lemmatize('fund'))
print(wnl.lemmatize('structure and utilization of the district mineral foundation'))
print(wnl.lemmatize('the socio-economic needs of affected communities' ))
print(wnl.lemmatize('the mineral conservation and development rules'))
print(wnl.lemmatize('1988'))
print(wnl.lemmatize('essential regulations' ))
print(wnl.lemmatize('guideline for navigating mining laws in india'))
print(wnl.lemmatize('mining regulation india'))
print(wnl.lemmatize('mining law compliance'))
print(wnl.lemmatize('mining lease application'))
print(wnl.lemmatize('environmental permit'))
print(wnl.lemmatize('mining safety regulation'))
print(wnl.lemmatize('mining license india'))
print(wnl.lemmatize('environmental impact assessment'))
print(wnl.lemmatize('corporate social responsibility (csr) in mining'))
print(wnl.lemmatize('guideline for mining'))
print(wnl.lemmatize('guideline' ))
print(wnl.lemmatize('default'))